package com.example.kilivana_driver.ui.screens.jobs

import androidx.lifecycle.ViewModel
import com.example.kilivana_driver.data.model.Job
import com.example.kilivana_driver.data.model.JobStatus
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update

data class JobsUiState(
    val selectedStatus: JobStatus = JobStatus.AVAILABLE,
    val jobs: List<Job> = emptyList()
) {
    val visibleJobs: List<Job>
        get() = jobs.filter { it.status == selectedStatus }

    fun countFor(status: JobStatus): Int = jobs.count { it.status == status }
}

class JobsViewModel : ViewModel() {

    // TODO: replace sample data with jobs from the API
    private val _uiState = MutableStateFlow(JobsUiState(jobs = sampleJobs()))
    val uiState: StateFlow<JobsUiState> = _uiState.asStateFlow()

    fun onStatusSelected(status: JobStatus) {
        _uiState.update { it.copy(selectedStatus = status) }
    }

    fun acceptJob(jobId: String) {
        // TODO: call the API to accept the job, then update on success
        _uiState.update { state ->
            state.copy(
                jobs = state.jobs.map { job ->
                    if (job.id == jobId) job.copy(status = JobStatus.ACCEPTED, isNew = false) else job
                },
                selectedStatus = JobStatus.ACCEPTED
            )
        }
    }

    fun completeJob(jobId: String) {
        // TODO: call the API to confirm delivery, then update on success
        _uiState.update { state ->
            state.copy(
                jobs = state.jobs.map { job ->
                    if (job.id == jobId) job.copy(status = JobStatus.COMPLETED) else job
                },
                selectedStatus = JobStatus.COMPLETED
            )
        }
    }
}

// TODO: deliveryOtp is a made-up sample here. In production this code is
// generated by the backend and sent to the BUYER by SMS once the driver
// marks the order as picked up — never shown to the driver in the UI.
internal fun sampleJobs(): List<Job> = listOf(
    Job(
        id = "AG-4589",
        pickupLocation = "Thika, Kiambu", pickupPlace = "Greenfield Farm", pickupTime = "Today 10:00 AM",
        pickupLat = -1.0332, pickupLon = 37.0693,
        dropoffLocation = "Nairobi, Nairobi", dropoffPlace = "Wakulima Market", dropoffTime = "Today 12:30 PM",
        dropoffLat = -1.2921, dropoffLon = 36.8219,
        cargo = "Vegetables (Mixed)", quantity = "1,000 kg",
        distanceKm = 45, estimatedTime = "1h 20m", payoutKsh = 2500,
        customer = "Greenfield Farm Ltd", deliveryOtp = "4821",
        status = JobStatus.AVAILABLE, isNew = true
    ),
    Job(
        id = "AG-4590",
        pickupLocation = "Mwea, Kirinyaga", pickupPlace = "Mwea Dairy Co-op", pickupTime = "Today 1:00 PM",
        pickupLat = -0.6839, pickupLon = 37.3556,
        dropoffLocation = "Nakuru, Nakuru", dropoffPlace = "Nakuru Dairy Hub", dropoffTime = "Today 4:40 PM",
        dropoffLat = -0.3031, dropoffLon = 36.0800,
        cargo = "Fresh Milk", quantity = "500 L",
        distanceKm = 205, estimatedTime = "3h 40m", payoutKsh = 3200,
        customer = "Mwea Dairy Co-op", deliveryOtp = "7734",
        status = JobStatus.AVAILABLE, isNew = true
    ),
    Job(
        id = "AG-4591",
        pickupLocation = "Machakos, Machakos", pickupPlace = "Machakos Grain Store", pickupTime = "Tomorrow 6:00 AM",
        pickupLat = -1.5177, pickupLon = 37.2634,
        dropoffLocation = "Kisumu, Kisumu", dropoffPlace = "Kisumu Grain Depot", dropoffTime = "Tomorrow 1:45 PM",
        dropoffLat = -0.0917, dropoffLon = 34.7680,
        cargo = "Dry Maize", quantity = "2,000 kg",
        distanceKm = 390, estimatedTime = "7h 45m", payoutKsh = 8500,
        customer = "Machakos Growers Ltd", deliveryOtp = "1029",
        status = JobStatus.AVAILABLE
    ),
    Job(
        id = "AG-4581",
        pickupLocation = "Kiambu, Kiambu", pickupPlace = "Kiambu Fresh Farm", pickupTime = "Yesterday 9:00 AM",
        pickupLat = -1.1714, pickupLon = 36.8356,
        dropoffLocation = "Nairobi, Nairobi", dropoffPlace = "City Market", dropoffTime = "Yesterday 10:00 AM",
        dropoffLat = -1.2921, dropoffLon = 36.8219,
        cargo = "Tomatoes", quantity = "800 kg",
        distanceKm = 32, estimatedTime = "55m", payoutKsh = 1900,
        customer = "Kiambu Fresh Farms", deliveryOtp = "3390",
        status = JobStatus.COMPLETED
    ),
    Job(
        id = "AG-4577",
        pickupLocation = "Nyeri, Nyeri", pickupPlace = "Highlands Farm", pickupTime = "Mon 7:30 AM",
        pickupLat = -0.4201, pickupLon = 36.9476,
        dropoffLocation = "Nairobi, Nairobi", dropoffPlace = "Wakulima Market", dropoffTime = "Mon 11:00 AM",
        dropoffLat = -1.2921, dropoffLon = 36.8219,
        cargo = "Potatoes", quantity = "1,500 kg",
        distanceKm = 155, estimatedTime = "3h 10m", payoutKsh = 4200,
        customer = "Highlands Growers", deliveryOtp = "5567",
        status = JobStatus.COMPLETED
    ),
    Job(
        id = "AG-4572",
        pickupLocation = "Naivasha, Nakuru", pickupPlace = "Naivasha Blooms", pickupTime = "Sun 5:00 AM",
        pickupLat = -0.7167, pickupLon = 36.4333,
        dropoffLocation = "Mombasa, Mombasa", dropoffPlace = "Mombasa Cargo Terminal", dropoffTime = "Sun 3:30 PM",
        dropoffLat = -4.0435, dropoffLon = 39.6682,
        cargo = "Cut Flowers", quantity = "300 kg",
        distanceKm = 480, estimatedTime = "9h 30m", payoutKsh = 9800,
        customer = "Naivasha Blooms Ltd", deliveryOtp = "8843",
        status = JobStatus.COMPLETED
    ),
    Job(
        id = "AG-4566",
        pickupLocation = "Embu, Embu", pickupPlace = "Embu Farm Collective", pickupTime = "Sat 8:00 AM",
        pickupLat = -0.5310, pickupLon = 37.4500,
        dropoffLocation = "Nairobi, Nairobi", dropoffPlace = "Marikiti Market", dropoffTime = "Sat 11:15 AM",
        dropoffLat = -1.2921, dropoffLon = 36.8219,
        cargo = "Bananas", quantity = "1,200 kg",
        distanceKm = 125, estimatedTime = "3h 15m", payoutKsh = 3600,
        customer = "Embu Farmers Co-op", deliveryOtp = "2214",
        status = JobStatus.COMPLETED
    ),
    Job(
        id = "AG-4561",
        pickupLocation = "Limuru, Kiambu", pickupPlace = "Limuru Dairy", pickupTime = "Fri 6:30 AM",
        pickupLat = -1.1122, pickupLon = 36.6438,
        dropoffLocation = "Nairobi, Nairobi", dropoffPlace = "Nairobi Milk Depot", dropoffTime = "Fri 7:45 AM",
        dropoffLat = -1.2921, dropoffLon = 36.8219,
        cargo = "Fresh Milk", quantity = "400 L",
        distanceKm = 28, estimatedTime = "1h 15m", payoutKsh = 1500,
        customer = "Limuru Dairy Ltd", deliveryOtp = "9081",
        status = JobStatus.COMPLETED
    )
)
